//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TursuBankAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kartlar
    {
        public int ID { get; set; }
        public Nullable<int> HesapID { get; set; }
        public string KartNo { get; set; }
        public string SonKullanimAy { get; set; }
        public string SonKullanimYil { get; set; }
        public string CVV { get; set; }
        public Nullable<bool> KartDurum { get; set; }
    
        public virtual Hesaplar Hesaplar { get; set; }
    }
}
